# Generated by Django 3.1.7 on 2021-03-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('identifier', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.TextField(default='')),
                ('Bib', models.CharField(max_length=30)),
                ('Authors', models.TextField(default='')),
                ('Keywords', models.TextField(default='')),
                ('Abstract', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('bib', models.CharField(default='', max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SourceB',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Object', models.CharField(max_length=100)),
                ('obsid', models.CharField(max_length=100)),
                ('RA', models.FloatField()),
                ('Dec', models.FloatField()),
                ('instrument', models.CharField(default='', max_length=50)),
                ('date_time', models.CharField(default='', max_length=30)),
                ('proposal_id', models.CharField(default='', max_length=50)),
                ('target_id', models.CharField(default='', max_length=200)),
                ('observer', models.CharField(default='', max_length=100)),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceA',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('RA', models.FloatField()),
                ('Dec', models.FloatField()),
                ('GLON', models.FloatField()),
                ('GLAT', models.FloatField()),
                ('Opt', models.CharField(max_length=100)),
                ('r_Opt', models.CharField(max_length=200)),
                ('Vmag', models.CharField(max_length=10)),
                ('B_V', models.FloatField(default=0)),
                ('U_B', models.CharField(max_length=10)),
                ('E_BV', models.CharField(max_length=10)),
                ('r_Vmag', models.CharField(max_length=200)),
                ('Fx', models.CharField(max_length=10)),
                ('Range', models.CharField(max_length=100)),
                ('r_Fx', models.CharField(max_length=200)),
                ('Porb', models.CharField(max_length=10)),
                ('Ppulse', models.CharField(max_length=10)),
                ('r_Ppulse', models.CharField(max_length=200)),
                ('Cat', models.CharField(max_length=100)),
                ('SpType', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('isObserved_uvit', models.BooleanField(default=False)),
                ('isObserved_sxt', models.BooleanField(default=False)),
                ('isObserved_laxpc', models.BooleanField(default=False)),
                ('isObserved_czti', models.BooleanField(default=False)),
                ('Publications', models.ManyToManyField(to='source.Publication')),
                ('czti', models.ManyToManyField(related_name='CZ', to='source.SourceB')),
                ('laxpc', models.ManyToManyField(related_name='PC', to='source.SourceB')),
                ('sxt', models.ManyToManyField(related_name='XT', to='source.SourceB')),
                ('uvit', models.ManyToManyField(related_name='UV', to='source.SourceB')),
            ],
        ),
    ]
