# Generated by Django 3.1.7 on 2021-03-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('identifier', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceB',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('RA', models.FloatField()),
                ('Dec', models.FloatField()),
                ('category', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SourceA',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('RA', models.FloatField()),
                ('Dec', models.FloatField()),
                ('isObserved_uvit', models.BooleanField(default=False)),
                ('isObserved_sxt', models.BooleanField(default=False)),
                ('isObserved_laxpc', models.BooleanField(default=False)),
                ('isObserved_czti', models.BooleanField(default=False)),
                ('category', models.CharField(default='', max_length=10)),
                ('Publications', models.ManyToManyField(to='source.Publication')),
                ('czti', models.ManyToManyField(related_name='CZ', to='source.SourceB')),
                ('laxpc', models.ManyToManyField(related_name='PC', to='source.SourceB')),
                ('sxt', models.ManyToManyField(related_name='XT', to='source.SourceB')),
                ('uvit', models.ManyToManyField(related_name='UV', to='source.SourceB')),
            ],
        ),
    ]
