# Generated by Django 3.1.7 on 2021-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcea',
            name='B_V',
            field=models.CharField(max_length=10),
        ),
    ]
